# Generated by Django 3.2.7 on 2021-10-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalLandTemperaturesByCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField()),
                ('AverageTemperature', models.FloatField(null=True)),
                ('AverageTemperatureUncertainty', models.FloatField(null=True)),
                ('City', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('Latitude', models.CharField(max_length=100)),
                ('Longitude', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'GlobalLandTemperaturesByCity',
                'verbose_name_plural': 'GlobalLandTemperaturesByCitys',
                'db_table': 'Global_Land_Temperatures_By_City',
                'managed': True,
            },
        ),
    ]
